version: 1
formatters:
  default:
    format: '%(levelname)-8s [%(asctime)s]: IN FUNCTION "%(funcName)s()": MESSAGE: "%(message)s"'
handlers:
  console:
    class: logging.StreamHandler
    formatter: default
    stream: ext://sys.stdout
  file:
    class: logging.FileHandler
    formatter: default
    filename: cdapython_log.txt
    encoding: utf8
    mode: a
loggers:
  default:
    handlers: [console]
    propagate: yes
